### ISSUE TITLE
Geoip & redir

### ISSUE THREAD

**Issue by Dragomir-Ivanov** [kodnaplakal/caddy-geoip#7]
Hi there,
Is there any way we can combine this plugin and `redir` plugin, so when we detect certain country say CY for Cyprus, to redirect the request from `/index.html` to `/cy/index.html`.
Thanks.

**Comment by aablinov** [comment]
Hi @Dragomir-Ivanov yes it's possible: https://caddy.community/t/how-to-use-geoip-for-geo-location-jumps/3603
