### ISSUE TITLE
Requests without a resolvable geoip should have a distinct value for placeholders

### ISSUE THREAD

**Issue by krader1961** [kodnaplakal/caddy-geoip#8]
I was using the MaxMind geoip databases when running a LAMP+Wordpress stack as an aid in understanding where requests were originating. So I was thrilled to find this plugin now that I've switched to Hugo+Caddy. One problem I've noticed is that using `{geoip_country_code}` in my `log` format string expands to nothing for requests from localhost. Failed geoip lookups should produce a distinct value for each placeholder that indicates why the lookup failed. If nothing else I'd like to see `{geoip_country_code}` resolve to something like `**` if the lookup failed. Whether distinct values for localhost versus all other IP addresses is needed is an open question.

**Comment by krader1961** [comment]
I forked this project and made the obvious, trivial, enhancement to solve my immediate need. I modified *setup.go*:

```
diff --git a/setup.go b/setup.go
index df94c2c..3af6799 100644
--- a/setup.go
+++ b/setup.go
@@ -89,7 +89,11 @@ func (gip GeoIP) lookupLocation(w http.ResponseWriter, r *http.Request) {
                log.Println(err)
        }

-       replacer.Set("geoip_country_code", record.Country.ISOCode)
+       if record.Country.ISOCode != "" {
+               replacer.Set("geoip_country_code", record.Country.ISOCode)
+       } else {
+               replacer.Set("geoip_country_code", "**")
+       }
        replacer.Set("geoip_country_name", record.Country.Names["en"])
        replacer.Set("geoip_country_eu", strconv.FormatBool(record.Country.IsInEuropeanUnion))
        replacer.Set("geoip_country_geoname_id", strconv.FormatUint(record.Country.GeoNameID, 10))
```

Ideally this logic would be abstracted into a function that wraps `gip.DBHandler.Lookup()` and which returns a `GeoIPRecord` with its members filled in with appropriate fallback values even if the MaxMindDB lookup doesn't have info for the IP address. Thus allowing this sequence of `replacer.Set()` calls to remain as is.

**Comment by aablinov** [comment]
Hi @krader1961 good job! But why not check it on the php side? Something like this:
`if empty($_SERVER['geoip_country_code']) { do_somethind }`

**Comment by krader1961** [comment]
> But why not check it on the php side?

Because a) I'm no longer using Wordpress (and thus no longer use PHP) and b) I want the info to show up in the access log. That is, in my caddy conf:

```
log / {$HOME}/log/access.log "{when_iso} {status} {method} {latency_ms} ms {size} bytes {geoip_country_code} {remote} {host} {proto} \"{uri}\" \"{>User-Agent}\""
```
